name: CI/CD

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy:
    name: Deploy app
    environment: 
      name: ${{ github.ref == 'refs/heads/development' && 'staging' || 'prod' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Set environment variable STAGE
      #   run: echo "STAGE=$(if [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then echo staging; elif [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then echo prod; fi)" >> $GITHUB_ENV

      - name: Print STAGE
        run: echo "Hello ${{ env.ENV_1 }}"
      
      - name: Print STAGE
        run: echo ${{ env.ENV_2 }}

      - name: Print STAGE
        run: echo ${{ env.ENV_3 }}

      # - name: Configure SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets[env.STAGE+'_SSH_KEY'] }}" > ~/.ssh/${{ env.STAGE }}.key
      #     chmod 600 ~/.ssh/${{ env.STAGE }}.key
      #     cat >>~/.ssh/config <<END
      #     Host ${{ env.STAGE }}
      #       HostName ${{ secrets[env.STAGE+'_SSH_HOST'] }}
      #       User ${{ secrets[env.STAGE+'_SSH_USER'] }}
      #       IdentityFile ~/.ssh/${{ env.STAGE }}.key
      #       StrictHostKeyChecking no
      #     END

      # - name: Stop the server
      #   run: ssh ${{ env.STAGE }} 'sudo systemctl stop my-application'

      # - name: Check out the source
      #   run: ssh ${{ env.STAGE }} 'cd my-application && git fetch && git reset --hard origin/master'

      # - name: Start the server
      #   if: ${{ always() }}
      #   run: ssh ${{ env.STAGE }} 'sudo systemctl start my-application'
