name: CI/CD

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy:
    name: Deploy app
    environment: 
      name: ${{ github.ref == 'refs/heads/development' && 'staging' || 'prod' }}
    runs-on: ubuntu-latest
    steps:

      - name: Set environment variable STAGE
        run: echo "STAGE=$(if [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then echo staging; elif [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then echo prod; fi)" >> $GITHUB_ENV
            
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ vars.SSH_KEY }}
          script: |
            pwd
            cd /var/www/bonzo && ls -la
            mkdir /var/www/bonzo/releases/$GITHUB_SHA

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: '${{ vars.SSH_KEY }}'
          source: "*"
          target: /var/www/bonzo/releases/$GITHUB_SHA

      # - name: ssh scp ssh pipelines
      #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      #   env:
      #     WELCOME: "ssh scp ssh pipelines"
      #     LASTSSH: "Doing something after copying"
      #   with:
      #     host: '${{ vars.SSH_HOST }}'
      #     user: '${{ vars.SSH_USER }}'
      #     key: '${{ vars.SSH_KEY }}'
      #     first_ssh: |
      #       ls -la  /var/www/bonzo
      #       mkdir /var/www/bonzo/releases/$GITHUB_SHA
      #     scp: |
      #       './.github/workflows/*' => /var/www/bonzo/releases/$GITHUB_SHA
      #       './templates/index.html' => /var/www/bonzo/releases/$GITHUB_SHA
      #       'README.md' => /var/www/bonzo/releases/$GITHUB_SHA
      #     last_ssh: |
      #       ls -la /var/www/bonzo/releases/$GITHUB_SHA

