name: CI/CD

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy:
    name: Deploy app
    environment: 
      name: ${{ github.ref == 'refs/heads/development' && 'staging' || 'prod' }}
    runs-on: ubuntu-latest
    steps:

      - name: Set environment variable STAGE
        run: echo "STAGE=$(if [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then echo staging; elif [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then echo prod; fi)" >> $GITHUB_ENV
      
      - uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          echo ${{ env.STAGE }}
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/${{ env.STAGE }}.key
          chmod 600 ~/.ssh/${{ env.STAGE }}.key
          cat >>~/.ssh/config <<END
          Host ${{ env.STAGE }}
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/${{ env.STAGE }}.key
            StrictHostKeyChecking no
          END

      - name: Download Artifacts into Environment
        run: |
          ssh ${{ env.STAGE }} 'pwd'

      - name: Deploy Web Artifact to Environment 
        run: |
           ssh ${{ env.STAGE }} 'cd /var/www/bonzo && ls -la'


      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ vars.SSH_HOST }}
      #     username: ${{ vars.SSH_USER }}
      #     key: ${{ vars.SSH_KEY }}
      #     script: |
      #       pwd
      #       cd /var/www/bonzo && ls -la

      # - name: Configure SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ vars.SSH_KEY }}" > ~/.ssh/${{ env.STAGE }}.key
      #     chmod 600 ~/.ssh/${{ env.STAGE }}.key
      #     cat >>~/.ssh/config <<END
      #     Host ${{ env.STAGE }}
      #       HostName ${{ vars.SSH_HOST }}
      #       User ${{ vars.SSH_USER }}
      #       IdentityFile ~/.ssh/${{ env.STAGE }}.key
      #       StrictHostKeyChecking no
      #     END

      # - name: Stop the server
      #   run: |
      #     ssh ${{ env.STAGE }} "pwd && cd /var/www/bonzo && ls -la"
