name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "rapita-flask-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-2"
  
  
on:
  push:
    branches: [ master ]
  
jobs:  
  ci_pipeline:   
    runs-on: ubuntu-latest

   
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3
    
    - name: Create ZIP feployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.gut*
      
    - name: Configure My AWS Ceredentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-acces-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print Happy Message for CI Finish
      run : echo "CI Pipeline part Finished succesfully!"
