name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "rapita-flask-application-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-2"
  
on:
  push:
    branches:
      - master
  
jobs:  
  ci_pipeline:   
    runs-on: ubuntu-latest

   
    steps:
    - name: Git clone our repo
    - uses: actions/checkout@v1
    
    - name: Create ZIP feployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.gut*
      
    
